### ISSUE TITLE
Bracket glow and closing bracket matcher not working

### ISSUE THREAD

**Issue by rgadd043** [augustovictor/atom-like-brackets-editor#5]
On initial install, it was working as designed. For some reason, it no longer is. I've uninstalled/reinstalled, still not working. Is there anything I can try? 

To be more specific, I do see a change in the line highlight, but the glow effect and 'matching' bracket highlighter is not working.

https://screencast.com/t/yP1vJtF8

**Comment by rgadd043** [comment]
To be more specific, I do see a change in the line highlight, but the glow effect and 'matching' bracket highlighter is not working. 

https://screencast.com/t/yP1vJtF8

**Comment by augustovictor** [comment]
Thanks for reaching out. I'll take a look at it.

Em 16 de mai de 2017 13:42, "Ryan Gadd" <notifications@github.com> escreveu:

**Comment by rgadd043** [comment]
Thanks for such a quick reply - here is another video, hope it's helpful. I don't think it's package conflict since I haven't changed anything, and did have it working prior. 

https://screencast.com/t/WWkfCKN4O7

**Comment by rgadd043** [comment]
It's working now, don't know if that's due to an Atom update or what, but we good. Cheers.
